# src/Esiea/BlogBundle/Resources/config/routing.yml

#esiea_blog_homepage:
  #  path:     /
   # defaults: { _controller: EsieaBlogBundle:Default:index }


esiea_blog_home:
    path:     /{page}
    defaults: { _controller: EsieaBlogBundle:Advert:index, page: 1 }
    requirements:
         page: \d*


esiea_blog_view:
    path:     /advert/{id}
    defaults: { _controller: EsieaBlogBundle:Advert:view }
    requirements:
        id: \d+


esiea_blog_edit:
    path:     /edit/{id}
    defaults: { _controller: EsieaBlogBundle:Advert:edit }
    requirements:
            id: \d+

esiea_blog_add:
    path:     /add
    defaults: { _controller: EsieaBlogBundle:Advert:add }


esiea_blog_delete:
    path:     /delete/{id}
    defaults: { _controller: EsieaBlogBundle:Advert:delete }
    requirements:
            id: \d+

